### PR TITLE
Resolves #69 for extra . after fields in contacts and groups

### LINKED ISSUE #69: Extra . after some fields
There is a . (period symbol) at the end of various fields in the Groups details screen.

**To Reproduce**
1. Go to the details screen of a group.
2. Click on Edit and adjust/set the group coach AND/OR Locations AND/OR people groups.
3. Click save, and you will be returned to the group details screen.
4. See that there is an extra . and the end of each field that was edited.

Screenshot_20191024-230318

### PR DESCRIPTION
**Pull request by mikeallbutt**

### CODE REVIEW

File: screens/Contact/ContactDetailScreen.js [hunk 1]
```diff
@@ -984,7 +984,7 @@ class ContactDetailScreen extends React.Component {
           </Col>
           <Col>
             <Text style={{ marginTop: 'auto', marginBottom: 'auto' }}>
-              {this.state.contact.subassigned ? this.state.contact.subassigned.values.map(contact => this.state.usersContacts.find(user => user.value === contact.value).name).join(', ') + (this.state.contact.subassigned.values.length > 0 ? '.' : '') : ''}
+              {this.state.contact.subassigned ? this.state.contact.subassigned.values.map(contact => this.state.usersContacts.find(user => user.value === contact.value).name).join(', ') + (this.state.contact.subassigned.values.length > 0 ? '' : '') : ''}
```
Comment (cairocoder01) [inline screens/Contact/ContactDetailScreen.js]: That whole ternary statement can just be remove since neither the true nor false condition add anything but an empty string.

Comment (mikeallbutt) [reply screens/Contact/ContactDetailScreen.js]: I have done as requested. All the extra length checks have been removed in the 2 files.
